@startuml

title Chess - Modelo de clases

Class Chess

Chess *--> Board
Chess *--> Player
Chess ..> Color
Chess ..> Console

Class Board

Board *--> Square
Board ..> Coordinate
Board ..> Color
Board ..> Piece
Board ..> King
Board ..> Queen
Board ..> Rook
Board ..> Bishop
Board ..> Knight
Board ..> Pawn
Board ..> Console
Board ..> MovementType

Class Player

Player *--> Color
Player ..> Board
Player ..> Coordinate
Player ..> Console
Player ..> Movement

Class Console

Enum Color

Class Square

Square --> Piece
Square *--> Coordinate
Square ..> Color
Square ..> Console
Square ..> MovementType

Class Coordinate

Coordinate ..> Console
Coordinate ..> LimitedIntDialog

Class Piece

Piece *--> Color
Piece ..> Coordinate

Class King

Piece <|-- King

Class Queen

Piece <|-- Queen

Class Rook

Piece <|-- Rook

Class Bishop

Piece <|-- Bishop

Class Knight

Piece <|-- Knight

Class Pawn

Piece <|-- Pawn

Class Movement

Movement --> Board
Movement *--> Coordinate
Movement *--> MovementType
Movement ..> Piece

Enum MovementType 

Class LimitedIntDialog

LimitedIntDialog *--> ClosedInterval
LimitedIntDialog ..> Console

Class ClosedInterval

@enduml
