@startuml

title Chess - Modelo de clases

Class Chess

Chess *--> Board
Chess *--> Player
Chess ..> Color
Chess ..> Console

Class Board

Board *--> Square
Board --> Color
Board --> Coordinate
Board ..> Piece
Board ..> King
Board ..> Queen
Board ..> Rook
Board ..> Bishop
Board ..> Knight
Board ..> Pawn
Board ..> Console

Class Player

Player *--> Color
Player --> Board
Player ..> Coordinate
Player ..> Console

Class Console

Enum Color

Class Square

Square *--> Piece
Square *--> Color
Square *--> Coordinate
Square ..> Console
Square ..> Movement

Class Coordinate

Coordinate ..> Console
Coordinate ..> LimitedIntDialog

Enum Movement

Class Piece

Piece *--> Color
Piece --> Coordinate
Piece --> Movement

Class King

Piece <|-- King

Class Queen

Piece <|-- Queen

Class Rook

Piece <|-- Rook

Class Bishop

Piece <|-- Bishop

Class Knight

Piece <|-- Knight

Class Pawn

Piece <|-- Pawn

Class LimitedIntDialog

LimitedIntDialog *--> ClosedInterval
LimitedIntDialog ..> Console

Class ClosedInterval

@enduml
